global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tunnel-server'
    scheme: https
    metrics_path: /api/metrics
    static_configs:
      - targets: ['tunnel.monday.app']
