name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: gcp
    steps:
      - uses: docker/login-action@v2
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@monday.com"
      - uses: nrwl/nx-set-shas@v2
      - run: npm ci
      - run: npx nx run-many --configuration=production --target=build --parallel=3
      - run: npm config --global set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - name: Version
        shell: bash
        run: npx nx run-many --parallel=1 --base=last-release --target=version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag last-release
        shell: bash
        run: |
          git tag -f last-release
          git push origin last-release --force
